return {}
-- return {
--     "elmcgill/springboot-nvim",
--     event = "VeryLazy",
--     config = function()
--         local springboot_nvim = require("springboot-nvim")
--
--         -- Set a vim motion to <Space> + <Shift>J + r to run the Spring Boot project in a vim terminal
--         vim.keymap.set("n", "<leader>Jr", springboot_nvim.boot_run, { desc = "[J]ava [R]un Spring Boot" })
--         -- Set a vim motion to <Space> + <Shift>J + c to open the generate class UI to create a class
--         vim.keymap.set("n", "<leader>Jc", springboot_nvim.generate_class, { desc = "[J]ava Create [C]lass" })
--         -- Set a vim motion to <Space> + <Shift>J + i to open the generate interface UI to create an interface
--         vim.keymap.set("n", "<leader>Ji", springboot_nvim.generate_interface, { desc = "[J]ava Create [I]nterface" })
--         -- Set a vim motion to <Space> + <Shift>J + e to open the generate enum UI to create an enum
--         vim.keymap.set("n", "<leader>Je", springboot_nvim.generate_enum, { desc = "[J]ava Create [E]num" })
--
--         -- Run the setup function with default configuration
--         springboot_nvim.setup({})
--     end,
-- }
